### Multiple Regression

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('mtcars.csv')

In [6]:
df

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [9]:
df.shapedf.

(32, 11)

In [10]:
df.corrwith(df['mpg'])

mpg     1.000000
cyl    -0.852162
disp   -0.847551
hp     -0.776168
drat    0.681172
wt     -0.867659
qsec    0.418684
vs      0.664039
am      0.599832
gear    0.480285
carb   -0.550925
dtype: float64

In [11]:
salary = pd.read_csv('Salary_Data.csv')

In [12]:
salary.corr()

                 YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [13]:
x = df[['disp', 'hp', 'wt']]
y = df['mpg']

In [14]:
x

     disp   hp     wt
0   160.0  110  2.620
1   160.0  110  2.875
2   108.0   93  2.320
3   258.0  110  3.215
4   360.0  175  3.440
5   225.0  105  3.460
6   360.0  245  3.570
7   146.7   62  3.190
8   140.8   95  3.150
9   167.6  123  3.440
10  167.6  123  3.440
11  275.8  180  4.070
12  275.8  180  3.730
13  275.8  180  3.780
14  472.0  205  5.250
15  460.0  215  5.424
16  440.0  230  5.345
17   78.7   66  2.200
18   75.7   52  1.615
19   71.1   65  1.835
20  120.1   97  2.465
21  318.0  150  3.520
22  304.0  150  3.435
23  350.0  245  3.840
24  400.0  175  3.845
25   79.0   66  1.935
26  120.3   91  2.140
27   95.1  113  1.513
28  351.0  264  3.170
29  145.0  175  2.770
30  301.0  335  3.570
31  121.0  109  2.780

### import the class

In [15]:
from sklearn.linear_model import LinearRegression

## Create the object

In [16]:
reg = LinearRegression()

### Train the model

In [18]:
reg.fit(x, y)

LinearRegression()

### predict on unseen data

In [19]:
disp = 221
hp = 102
wt = 2.91
reg.predict([[disp, hp, wt]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22.65986648])